#!/usr/bin/env python3
"""Integration tests for first-run setup wizard + server first-run detection.

Ported to the post-Plan-001 consolidated API. Covers:
- First-run detection (check_first_run)
- End-to-end setup flow (config + auth creation)
- CLI entry points (run_setup_wizard)
"""

import json
import os
import sys
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

sys.path.insert(0, str(Path(__file__).parent.parent))

from first_run import check_first_run, ensure_configured_or_exit
from setup_wizard import (
    create_auth_file,
    generate_password,
    run_setup_wizard,
    prompt_with_default,
    prompt_yes_no,
)
from config_schema import CompanionConfig, save_config, CONFIG_DIR, CONFIG_FILE


# ── First-run detection ─────────────────────────────────────────

class TestFirstRunDetection:
    """Test that server detects missing config and exits with code 2."""

    def test_server_exits_code_2_without_config(self, tmp_path):
        """check_first_run() should return True when no config file exists."""
        import config_schema
        original = config_schema.CONFIG_FILE
        config_schema.CONFIG_FILE = tmp_path / "nonexistent.yaml"
        try:
            result = check_first_run()
        finally:
            config_schema.CONFIG_FILE = original
        assert result is True

    def test_server_continues_with_config(self, tmp_path):
        """check_first_run() should return False when config file exists."""
        import config_schema
        original = config_schema.CONFIG_FILE
        cfg = tmp_path / "config.yaml"
        cfg.write_text("server:\n  host: 127.0.0.1\n  port: 8777\n")
        config_schema.CONFIG_FILE = cfg
        try:
            result = check_first_run()
        finally:
            config_schema.CONFIG_FILE = original
        assert result is False


# ── End-to-end setup ────────────────────────────────────────────

class TestEndToEndSetup:
    """End-to-end: setup wizard -> config -> server can load config."""

    def test_setup_generates_loadable_config(self, tmp_path):
        """Config generated by setup wizard can be loaded by config_schema."""
        from unittest.mock import patch as _patch

        config = CompanionConfig()
        config.server.host = "127.0.0.1"
        config.server.port = 8777
        config.hermes.api_url = "http://127.0.0.1:8642"
        config.hermes.api_key = "test-key"
        config.hermes.cli_path = "/usr/bin/hermes"
        config.auth.file = str(tmp_path / "auth.json")
        config.storage.attachments_dir = str(tmp_path / "attachments")

        import config_schema
        orig_file = config_schema.CONFIG_FILE
        orig_dir = config_schema.CONFIG_DIR
        config_schema.CONFIG_FILE = tmp_path / "config.yaml"
        config_schema.CONFIG_DIR = tmp_path
        try:
            save_config(config)
        finally:
            config_schema.CONFIG_FILE = orig_file
            config_schema.CONFIG_DIR = orig_dir

        data = yaml.safe_load((tmp_path / "config.yaml").read_text())
        assert data["server"]["host"] == "127.0.0.1"
        assert data["server"]["port"] == 8777
        assert data["hermes"]["api_url"] == "http://127.0.0.1:8642"

    def test_auth_json_format_matches_server_expectations(self, tmp_path):
        """Auth.json from setup wizard matches what server expects."""
        from unittest.mock import patch as _patch

        config = CompanionConfig()
        config.auth.file = str(tmp_path / "auth.json")

        with _patch("setup_wizard.hash_password", return_value="scrypt$131072$8$1$salthex$hashb64"):
            create_auth_file(config, "admin", "testpass123")

        data = json.loads(Path(config.auth.file).read_text())
        assert "users" in data
        assert "admin" in data["users"]
        pw_hash = data["users"]["admin"]["password_hash"]

        # Must match server format: scrypt$N$r$p$salt$hash
        parts = pw_hash.split("$")
        assert parts[0] == "scrypt"
        assert len(parts) == 6

    def test_full_setup_wizard_flow(self, tmp_path):
        """Simulate full wizard flow: config + auth + attachments created."""
        import config_schema
        orig_dir = config_schema.CONFIG_DIR
        orig_file = config_schema.CONFIG_FILE
        config_schema.CONFIG_DIR = tmp_path
        config_schema.CONFIG_FILE = tmp_path / "config.yaml"

        auth_path = tmp_path / "auth.json"

        try:
            with patch("setup_wizard.detect_hermes_cli", return_value=Path("/usr/bin/hermes")):
                with patch("setup_wizard.hash_password", return_value="scrypt$131072$8$1$salthex$hashb64"):
                    with patch("setup_wizard.prompt_with_default", return_value=""):
                        with patch("setup_wizard.prompt_yes_no", return_value=True):
                            with patch("setup_wizard.create_auth_file") as mock_auth:
                                mock_auth.side_effect = lambda cfg, user, pw: auth_path
                                result = run_setup_wizard()
        finally:
            config_schema.CONFIG_DIR = orig_dir
            config_schema.CONFIG_FILE = orig_file

        assert result == 0
        assert (tmp_path / "config.yaml").exists()

    def test_config_yaml_roundtrip(self, tmp_path):
        """Config survives YAML roundtrip with all expected keys."""
        config = CompanionConfig()
        config.server.host = "0.0.0.0"
        config.server.port = 9090
        config.hermes.api_url = "http://192.168.1.100:8642"
        config.hermes.api_key = "secret123"
        config.hermes.cli_path = "/home/user/.hermes/hermes-agent/venv/bin/hermes"
        config.auth.file = "~/.config/hermes-companion/auth.json"
        config.storage.attachments_dir = "~/.config/hermes-companion/attachments"

        import config_schema
        orig_file = config_schema.CONFIG_FILE
        orig_dir = config_schema.CONFIG_DIR
        config_schema.CONFIG_FILE = tmp_path / "config.yaml"
        config_schema.CONFIG_DIR = tmp_path
        try:
            save_config(config)
        finally:
            config_schema.CONFIG_FILE = orig_file
            config_schema.CONFIG_DIR = orig_dir

        data = yaml.safe_load((tmp_path / "config.yaml").read_text())
        assert data["server"]["host"] == "0.0.0.0"
        assert data["server"]["port"] == 9090
        assert data["hermes"]["api_url"] == "http://192.168.1.100:8642"
        assert data["hermes"]["api_key"] == "secret123"
        assert data["hermes"]["cli_path"] == "/home/user/.hermes/hermes-agent/venv/bin/hermes"
        assert data["auth"]["file"] == "~/.config/hermes-companion/auth.json"
        assert data["storage"]["attachments_dir"] == "~/.config/hermes-companion/attachments"
        assert data["storage"]["max_upload_size"] == 10485760


# ── CLI entry points ────────────────────────────────────────────

class TestCliEntryPoints:
    """Test CLI entry points via run_setup_wizard."""

    def test_setup_non_interactive(self, tmp_path):
        """run_setup_wizard creates config and auth files."""
        import config_schema
        orig_dir = config_schema.CONFIG_DIR
        orig_file = config_schema.CONFIG_FILE
        config_schema.CONFIG_DIR = tmp_path
        config_schema.CONFIG_FILE = tmp_path / "config.yaml"

        try:
            with patch("setup_wizard.detect_hermes_cli", return_value=Path("/usr/bin/hermes")):
                with patch("setup_wizard.hash_password", return_value="scrypt$131072$8$1$salthex$hashb64"):
                    with patch("setup_wizard.prompt_with_default", return_value=""):
                        with patch("setup_wizard.prompt_yes_no", return_value=True):
                            result = run_setup_wizard()
        finally:
            config_schema.CONFIG_DIR = orig_dir
            config_schema.CONFIG_FILE = orig_file

        assert result == 0
        assert (tmp_path / "config.yaml").exists()

    def test_no_args_returns_0(self):
        """run_setup_wizard with existing config and 'no' to overwrite returns 0."""
        import config_schema
        orig_dir = config_schema.CONFIG_DIR
        orig_file = config_schema.CONFIG_FILE

        # Use the real CONFIG_FILE which already exists
        try:
            with patch("setup_wizard.prompt_yes_no", return_value=False):
                result = run_setup_wizard()
        finally:
            config_schema.CONFIG_DIR = orig_dir
            config_schema.CONFIG_FILE = orig_file

        assert result == 0
