#!/usr/bin/env python3
"""Integration tests for first-run setup wizard + server first-run detection."""

import json
import os
import sys
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

sys.path.insert(0, str(Path(__file__).parent.parent))


class TestFirstRunDetection:
    """Test that server exits with code 2 when no config.yaml exists."""

    def test_server_exits_code_2_without_config(self, tmp_path):
        """Server main() should exit(2) when no config file is found."""
        from server import check_first_run

        with patch("config.find_config_path", return_value=None):
            result = check_first_run()

        assert result is True

    def test_server_continues_with_config(self, tmp_path):
        """Server main() should not exit when config file exists."""
        from server import check_first_run

        cfg = tmp_path / "config.yaml"
        cfg.write_text("server:\n  host: 127.0.0.1\n  port: 8777\n")

        with patch("config.find_config_path", return_value=cfg):
            result = check_first_run()

        assert result is False


class TestEndToEndSetup:
    """End-to-end: setup wizard -> config -> server can load config."""

    def test_setup_generates_loadable_config(self, tmp_path):
        """Config generated by setup wizard can be loaded by config.py."""
        from setup_wizard import create_config_yaml, create_auth_json

        config_path = tmp_path / "config.yaml"
        auth_path = tmp_path / "auth.json"

        create_config_yaml(
            dest=config_path,
            server_host="127.0.0.1",
            server_port=8777,
            hermes_api_url="http://127.0.0.1:8642",
            hermes_api_key="test-key",
            hermes_binary_path="/usr/bin/hermes",
            auth_file_path=str(auth_path),
            attachments_dir=str(tmp_path / "attachments"),
        )

        create_auth_json(auth_path, "admin", "testpass123")

        # Verify config loads
        from config import load_config

        with patch("config.find_config_path", return_value=config_path):
            with patch.dict(os.environ, {"API_SERVER_KEY": "test-key"}):
                config = load_config()

        assert config["server"]["host"] == "127.0.0.1"
        assert config["server"]["port"] == 8777
        assert config["hermes"]["api_url"] == "http://127.0.0.1:8642"

    def test_auth_json_format_matches_server_expectations(self, tmp_path):
        """Auth.json from setup wizard matches what server.py expects."""
        from setup_wizard import create_auth_json

        auth_path = tmp_path / "auth.json"
        create_auth_json(auth_path, "admin", "testpass123")

        data = json.loads(auth_path.read_text())
        assert "users" in data
        assert "admin" in data["users"]
        pw_hash = data["users"]["admin"]["password_hash"]

        # Must match server.py format: scrypt$N$r$p$salt$hash
        parts = pw_hash.split("$")
        assert parts[0] == "scrypt"
        assert len(parts) == 6

    def test_full_setup_wizard_flow(self, tmp_path):
        """Simulate full wizard flow: config + auth + attachments created."""
        from setup_wizard import run_wizard

        # Simulate user pressing Enter for all defaults
        inputs = iter([
            "",          # host (default 127.0.0.1)
            "",          # port (default 8777)
            "",          # hermes API URL
            "",          # API key (empty)
            "",          # hermes binary (detected)
            "",          # username (default admin)
            "",          # accept generated password (no custom)
            "",          # auth file path (default)
            "",          # attachments dir (default)
        ])

        with patch("builtins.input", lambda _: next(inputs)):
            with patch("setup_wizard.detect_hermes_binary", return_value="/usr/bin/hermes"):
                result = run_wizard(
                    config_dir=tmp_path,
                    username="admin",
                    board="default",
                    skip_qr=True,
                )

        assert result["config_path"].exists()
        assert result["auth_path"].exists()
        assert result["password"] is not None
        assert len(result["password"]) > 0
        assert result["username"] == "admin"
        assert "127.0.0.1:8777" in result["server_url"]

    def test_config_yaml_roundtrip(self, tmp_path):
        """Config survives YAML roundtrip with all expected keys."""
        from setup_wizard import create_config_yaml

        config_path = tmp_path / "config.yaml"
        create_config_yaml(
            dest=config_path,
            server_host="0.0.0.0",
            server_port=9090,
            hermes_api_url="http://192.168.1.100:8642",
            hermes_api_key="secret123",
            hermes_binary_path="/home/user/.hermes/hermes-agent/venv/bin/hermes",
            auth_file_path="~/.config/hermes-companion/auth.json",
            attachments_dir="~/.config/hermes-companion/attachments",
        )

        data = yaml.safe_load(config_path.read_text())
        assert data["server"]["host"] == "0.0.0.0"
        assert data["server"]["port"] == 9090
        assert data["hermes"]["api_url"] == "http://192.168.1.100:8642"
        assert data["hermes"]["api_key"] == "secret123"
        assert data["hermes"]["binary_path"] == "/home/user/.hermes/hermes-agent/venv/bin/hermes"
        assert data["auth"]["file_path"] == "~/.config/hermes-companion/auth.json"
        assert data["attachments"]["dir"] == "~/.config/hermes-companion/attachments"
        assert data["attachments"]["max_upload_mb"] == 25


class TestCliEntryPoints:
    """Test CLI subcommands."""

    def _load_cli(self):
        import importlib.util
        import sys
        src_dir = str(Path(__file__).parent.parent / "src")
        if src_dir not in sys.path:
            sys.path.insert(0, src_dir)
        from hermes_companion import cli
        return cli

    def test_setup_non_interactive(self, tmp_path):
        cli = self._load_cli()
        result = cli.main(["setup", "--non-interactive", "--config-dir", str(tmp_path)])
        assert result == 0
        assert (tmp_path / "config.yaml").exists()
        assert (tmp_path / "auth.json").exists()

    def test_no_args_returns_0(self):
        cli = self._load_cli()
        result = cli.main([])
        assert result == 0
